import "GroupAudioCallViewModel.idl";

namespace GroupAudioCallWinUI3Cpp {
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window {
        MainWindow();
        Int32 MyProperty;

        GroupAudioCallViewModel CallViewModel{ get; };
    }
}
