// Copyright 2024 LINE Plus Corporation
// 
// LINE Plus Corporation licenses this file to you under the Apache License,
// version 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at:
// 
//   https://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

#pragma once

namespace GroupAudioCall {
    constexpr wchar_t USER_ID[] = L""; // Copy and paste the user ID that you used when generating access token.
    constexpr wchar_t ACCESS_TOKEN[] = L""; // Copy and paste the access token generated by the tool.

    constexpr wchar_t SERVICE_ID[] = L"planet-kit-quick-start";
    constexpr wchar_t PLANET_CLOUD_URL[] = L"https://voipnx-saturn.line-apps.com";
};