#pragma once

namespace GroupAudioCall {
    constexpr wchar_t USER_ID[] = L""; // Copy and paste the user ID that you used when generating access token.
    constexpr wchar_t ACCESS_TOKEN[] = L""; // Copy and paste the access token generated by the tool.

    constexpr wchar_t SERVICE_ID[] = L"planet-kit-quick-start";
    constexpr wchar_t PLANET_CLOUD_URL[] = L"https://voipnx-saturn.line-apps.com";
};